app/models.py
from app import db

class Todo(db.Model):
  id = db.Column(db.Integer, primary_key=True)
  content = db.Column(db.Text, nullable = False)

  def __repr__(self):
    return(f"Todo('{self.id}', '{self.content}')")

app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
  todo = StringField('toDos', validators=[DataRequired()])
  submit = SubmitField('submit')

app/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from app.config import configs

db = SQLAlchemy()
boostrap = Bootstrap()

def create_app(config_name='development'):
  app = Flask(__name__)
  app.config.from_object(configs.get(config_name))
  
  db.init_app(app)
  boostrap.init_app(app)

  from app.main.routes import main
  from app.posts.routes import post

  app.register_blueprint(main)
  app.register_blueprint(post)
  
  return app

app/main/routes.py
from flask import Blueprint, render_template
from app.models import Todo

main = Blueprint('main', __name__)

@main.route('/')
def index():
  todos = Todo.query.order_by(Todo.id.desc()).all()
  return render_template('index.html', todos=todos)

app/posts/routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from .forms import PostForm
from app import db
from app.models import Todo

post = Blueprint('post', __name__)

@post.route('/new', methods=['GET'])
def new():
  post_form = PostForm()
  return render_template('new.html', post_form = post_form)

@post.route('/create', methods=['POST'])
def create():
  post_form = PostForm()
  if request.method == 'POST' and post_form.validate_on_submit():
    to_do = Todo(content = post_form.todo.data)
    db.session.add(to_do)
    db.session.commit()
    return redirect(url_for('main.index'))

@post.route('/<int:id>')
def show(id):
  data = Todo.query.filter_by(id=id).first()
  return render_template('show.html', data=data)

@post.route('/<int:id>/edit')
def edit(id):
  edit_form = PostForm()
  get_todo_data = Todo.query.filter_by(id=id).first()
  edit_form.todo.data = get_todo_data.content
  return render_template('edit.html', edit_form=edit_form, id=id)

@post.route('/<int:id>', methods=['POST'])
def update(id):
  form = PostForm()
  new_update = Todo.query.filter_by(id=id).first()
  new_update.content = form.todo.data 
  db.session.commit()
  return redirect(url_for('main.index'))

@post.route('/delete/<int:id>')
def destroy(id):
  delete_todo = Todo.query.filter_by(id=id).first()
  db.session.delete(delete_todo)
  db.session.commit()
  return redirect(url_for('main.index'))

app/templates/edit.html
{% extends 'layout.html' %}

{% block content %}
  <div class="container">
    <form action={{ url_for('post.update', id=id) }} method="POST" class="form">
      {{ edit_form.todo(class='form form-control') }}
      {{ edit_form.submit(class='btn btn-warning newsubmit') }}
    </form>
    <p class="links resize-p-tag"><a href={{ url_for('main.index')}}>cancel</a></p>
  </div>
{% endblock content %}

app/templates/index.html
{% extends 'layout.html' %}

{%block content%}
<div class="container">
  {% if todos| length > 0 %}
    <ul id='todo'>
      {% for todo in todos %}
        <li id='todo-element'><a href={{ url_for('post.show', id=todo.id )}}>{{ todo.content }}</a></li>
      {% endfor %}
    </ul>
  {% endif%}
  <span class='links'><a href={{ url_for('post.new') }}>create post</a></span>
</div>
{%endblock content%}

app/templates/layout.html
{% extends 'bootstrap/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  {% block styles %}
   {{ super()}}
   <link rel="stylesheet" href="{{url_for('static', filename='layout.css')}}"> 
  {% endblock styles %}
</head>
<body>
  {%block content%}{%endblock content%}
</body>
</html>

app/templates/new.html
{% extends 'layout.html'%}

{% block content %}
<div class="container">
  <form method="POST" action="/create" class="form">
    {{ post_form.csrf_token }}
    {{ post_form.todo(class='form-control form-control-sm', placeholder='what is on your mind?') }}
    {{ post_form.submit(class='btn btn-warning') }}
  </form>
  <p class="links resize-p-tag"><a href={{ url_for('main.index')}}>Back to home</a></p>
</div>
{%endblock content%}

app/templates/show.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
{% if data %}
  <div class="wrapper">
    <p class="todo-element">{{ data.content }}</p>
  </div>
  <div class="show-links">
    <p class="links resize-p-tag"><a href={{ url_for('post.edit', id=data.id )}}>edit</a></p>
    <p class="links resize-p-tag"><a href={{ url_for('post.destroy', id=data.id )}}>delete</a></p>
    <p class="links resize-p-tag"><a href={{ url_for('main.index')}}>Back to home</a></p>  
  </div>
{% else %}
  <span> Sorry, the post was not found</span>
  <p class="links resize-p-tag"><a href={{ url_for('main.index')}}>Back to home</a></p>
{% endif%}
</div>
{% endblock content %}